project_name: tmux-fastcopy

before:
  hooks:
    # Verify that the version number in the install.sh matches the planned
    # version.
    - ./install.sh -c {{.Version}}

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - windows
      - darwin
    goarm: [5, 6, 7]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    ldflags: '-s -w -X main._version={{.Version}}'

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

aurs:
  - name: tmux-fastcopy-bin
    homepage: https://github.com/abhinav/tmux-fastcopy
    description: "easymotion-style text copying for tmux."
    maintainers:
      - 'Abhinav Gupta <mail@abhinavg.net>'
    license: "MIT"
    git_url: "ssh://aur@aur.archlinux.org/tmux-fastcopy-bin.git"
    skip_upload: auto
    private_key: '{{ .Env.AUR_KEY }}'
    package: |-
      install -Dm755 "./tmux-fastcopy" "${pkgdir}/usr/bin/tmux-fastcopy"
      install -Dm755 "./LICENSE" "${pkgdir}/usr/share/licenses/tmux-fastcopy/LICENSE"
    commit_author:
      name: Abhinav Gupta
      email: mail@abhinavg.net

brews:
  - tap:
      owner: abhinav
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "{{ .ProjectName }}: Update formula to {{ .Tag }}"
    commit_author:
      name: Abhinav Gupta
      email: mail@abhinavg.net
    homepage: https://github.com/abhinav/tmux-fastcopy
    description: "easymotion-style text copying for tmux."
    license: "MIT"
    skip_upload: auto
    dependencies:
      - name: tmux
    test: |
      system "#{bin}/tmux-fastcopy -version"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incminor .Tag }}-dev"
