// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/abhinav/tmux-fastcopy/internal/fastcopy (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -destination mock_handler_test.go -package fastcopy github.com/abhinav/tmux-fastcopy/internal/fastcopy Handler
//

// Package fastcopy is a generated GoMock package.
package fastcopy

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleSelection mocks base method.
func (m *MockHandler) HandleSelection(arg0 Selection) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleSelection", arg0)
}

// HandleSelection indicates an expected call of HandleSelection.
func (mr *MockHandlerMockRecorder) HandleSelection(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSelection", reflect.TypeOf((*MockHandler)(nil).HandleSelection), arg0)
}
