name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

env:
  GO_VERSION: 1.20.x

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out repository
    - uses: actions/setup-go@v4
      name: Set up Go
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    - uses: golangci/golangci-lint-action@v3
      name: Install golangci-lint
      with:
        version: latest
        args: --version
    - run: make lint
      name: Lint

  docs:
    name: Check documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      name: Check out repository
    - name: Check or update documentation
      uses: abhinav/stitchmd-action@v1
      with:
        summary: doc/README.md
        output: README.md
        mode: ${{ github.event_name == 'pull_request' && 'write' || 'check' }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: README.md
        commit_message: 'Update README.md'

  test:
    runs-on: ubuntu-latest
    name: Unit Test

    steps:
    - uses: actions/checkout@v3
      name: Check out repository
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Build tmux-fastcopy
      run: make build
    - name: Test
      run: PATH="$HOME/.local/bin:$PATH" make cover
    - name: Coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./cover.out

  integration:
    runs-on: ubuntu-latest
    name: Integration Test / Tmux ${{ matrix.tmux-version }}
    strategy:
      matrix:
        tmux-version: ["3.2a", "3.1c", "3.0a", "2.9a", "2.8", "2.7"]

    steps:
    - uses: actions/checkout@v3
      name: Check out repository
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Checkout Tmux
      uses: actions/checkout@v3
      with:
        repository: tmux/tmux
        ref: ${{ matrix.tmux-version }}
        path: src/tmux
    - name: Load cached Tmux
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: ${{ runner.os }}-tmux-${{ matrix.tmux-version }}

    - name: Download and install dependencies
      run: |
        sudo apt-get install -y libevent-dev libncurses-dev
    - name: Install Tmux
      working-directory: src/tmux
      run: |
        if [[ ! -x "$HOME/.local/bin/tmux" ]]; then
          sh autogen.sh
          ./configure --prefix="$HOME/.local"
          make install
        else
          echo "Using cached tmux"
        fi

    - name: Build tmux-fastcopy
      run: make build

    - name: Integration test
      run: make cover-integration
    - name: Coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./cover.integration.out
