name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tmux-version: ["3.2a", "3.1c", "3.0a", "2.9a", "2.8", "2.7"]

    name: Test / Tmux ${{ matrix.tmux-version }}

    steps:

    - uses: actions/checkout@v3

    - name: Checkout Tmux
      uses: actions/checkout@v3
      with:
        repository: tmux/tmux
        ref: ${{ matrix.tmux-version }}
        path: src/tmux

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
        cache: true

    - name: Load cached Tmux
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: ${{ runner.os }}-tmux-${{ matrix.tmux-version }}

    - name: Download and install dependencies
      run: |
        go mod download
        sudo apt-get install -y libevent-dev libncurses-dev

    - name: Install Tmux
      working-directory: src/tmux
      run: |
        if [[ ! -x "$HOME/.local/bin/tmux" ]]; then
          sh autogen.sh
          ./configure --prefix=$HOME/.local
          make install
        else
          echo "Using cached tmux"
        fi

    - name: Build tmux-fastcopy
      run: make build

    - name: Lint
      run: make lint

    - name: Test
      run: PATH="$HOME/.local/bin:$PATH" make cover

    - name: Coverage
      uses: codecov/codecov-action@v3
