name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.x

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Load cached dependencies
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Prepare release
      run: |
        set -eou pipefail
        make bin/extract-changelog
        VERSION=${{ github.ref }}
        VERSION="${VERSION#refs/tags/}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Releasing $VERSION"
        echo "Release notes:"
        echo "----"
        bin/extract-changelog $VERSION | tee changes.$VERSION.txt
        echo "----"

    - name: Release
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist --release-notes changes.${{ env.VERSION }}.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AUR_KEY: ${{ secrets.AUR_KEY }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        GORELEASER_CURRENT_TAG: ${{ env.VERSION }}
