name: Stitch README.md

on:
  push:
    branches: [main]

  pull_request:

jobs:
  stitchmd:
    name: ${{ github.event_name == 'pull_request' && 'Update' || 'Check' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v6
    - name: Check or update README
      uses: abhinav/stitchmd-action@v2
      with:
        mode: ${{ github.event_name == 'pull_request' && 'write' || 'check' }}
        summary: doc/README.md
        output: README.md

    - uses: stefanzweifel/git-auto-commit-action@v7
      if: ${{ github.event_name == 'pull_request' }}
      with:
        file_pattern: README.md
        commit_message: 'Update README.md'
